function change_language_english()
{
    var en = document.getElementById("english");
    var vn = document.getElementById("vietnamese");
    en.classList.toggle("choose_language");
    en.classList.toggle("unchoose_language");
    vn.classList.toggle("choose_language");
    vn.classList.toggle("unchoose_language");
    var enm = document.getElementById("english_mobile");
    var vnm = document.getElementById("vietnamese_mobile");
    enm.classList.toggle("choose_language");
    enm.classList.toggle("unchoose_language");
    vnm.classList.toggle("choose_language");
    vnm.classList.toggle("unchoose_language");
    document.getElementById("home_page").innerHTML = "HOME";
    document.getElementById("repices_page").innerHTML = "REPICES";
    document.getElementById("order_page").innerHTML = "ORDER";
    document.getElementById("news_page").innerHTML = "NEWS";
    document.getElementById("home_page_mobile").innerHTML = "HOME";
    document.getElementById("repices_page_mobile").innerHTML = "REPICES";
    document.getElementById("order_page_mobile").innerHTML = "ORDER";
    document.getElementById("news_page_mobile").innerHTML = "NEWS";
    document.getElementById("register_text").innerHTML = "Register";
    document.getElementById("login_text").innerHTML = "Login";
    document.getElementById("register_text_mobile").innerHTML = "Register";
    document.getElementById("login_text_mobile").innerHTML = "Login";
    document.getElementById("title_banner_1").innerHTML="EXPLORER TEYVAT";
    document.getElementById("title_banner_2").innerHTML="40+ NEW REPICES";
    document.getElementById("title_banner_3").innerHTML="TASTY & NUTRITIOUS MEALS";
    document.getElementById("description_banner_1").innerHTML="5000+ NEWS EVERYDAY";
    document.getElementById("description_banner_2").innerHTML="ALL REPICES OF TEYVAT";
    document.getElementById("description_banner_3").innerHTML="YET AFFORDABLE";
    document.getElementById("more_button_1").innerHTML="See More";
    document.getElementById("more_button_2").innerHTML="See Now";
    document.getElementById("more_button_3").innerHTML="Order Now";
    document.getElementById("About_us_des").innerHTML="&nbsp;On the adventure of traveler food has become a isdispensable and important<br> friend, <b>TEYVAT</b> <font style='color: rgb(44, 117, 44);font-weight: bold;'>FOOD</font>  here helps travelers get the newest information of<br>Most useful about foods <i>(Recipes, BUFF of foods...and many thing else).</i><br> <br>&nbsp;Besides that <b>TEYVAT</b> <font style='color: rgb(44, 117, 44);font-weight: bold;'>FOOD</font> not only supports you mentally but also mentally<br> physical side. We provide fresh, naturally and nutritious meals inspired by<br> original inspiration in <b>Genshin Impact</b> to give you the best experience.";
    document.getElementById("Hot_Repices_Title").innerHTML="FEATURED REPICES";
    document.getElementById("name_repices_1").innerHTML="Adeptus' Temptation";
    document.getElementById("name_repices_2").innerHTML="Bountiful Year";
    document.getElementById("name_repices_3").innerHTML="A Buoyant Breeze";
    document.getElementById("name_repices_4").innerHTML="Ghostly March";
    document.getElementById("Hot_Food_tittle").innerHTML="FEATURED FOOD";
    document.getElementById("Protect_enviroment_title").innerHTML="ENVIRONMENTAL FRIENDLY";
    document.getElementById("linking_partner").innerHTML="PARTNERS";
    document.getElementById("linking_customer").innerHTML="CLIENTS";
    document.getElementById("footer_des_1").innerHTML="<font style='font-weight: bold;color: rgb(172, 222, 223);font-size: 1.2vw;'>TEYVATFOOD COMPANY LIMITED</font>";
    document.getElementById("footer_des_2").innerHTML="<font style='font-weight: bold;'>Address</font> 33 Đường X, KDC Bình Hưng A, Ấp 2, Huyện Bình Chánh A, TP.X";
    document.getElementById("footer_des_3").innerHTML="<font style='font-weight: bold;'>Phone</font> (+84) 932 788 120 [hotline]";
    document.getElementById("footer_des_5").innerHTML="<font style='font-weight: bold;'>Tax Code</font> 0313272749 do Sở kế hoạch và đầu tư TPHCM cấp ngày dd/mm/yyyy";
    document.getElementById("footer_des_7").innerHTML="<font style='font-weight: bold;color: rgb(172, 222, 223);font-size: 1.2vw;'>TERMS AND CONDITIONS</font>";
}
function change_language_vietnamese()
{
    var en = document.getElementById("english");
    var vn = document.getElementById("vietnamese");
    en.classList.toggle("choose_language");
    en.classList.toggle("unchoose_language");
    vn.classList.toggle("choose_language");
    vn.classList.toggle("unchoose_language");
    var enm = document.getElementById("english_mobile");
    var vnm = document.getElementById("vietnamese_mobile");
    enm.classList.toggle("choose_language");
    enm.classList.toggle("unchoose_language");
    vnm.classList.toggle("choose_language");
    vnm.classList.toggle("unchoose_language");
    document.getElementById("home_page").innerHTML = "TRANG CHỦ";
    document.getElementById("repices_page").innerHTML = "CÔNG THỨC";
    document.getElementById("order_page").innerHTML = "ĐẶT HÀNG";
    document.getElementById("news_page").innerHTML = "TIN TỨC";
    document.getElementById("home_page_mobile").innerHTML = "TRANG CHỦ";
    document.getElementById("repices_page_mobile").innerHTML = "CÔNG THỨC";
    document.getElementById("order_page_mobile").innerHTML = "ĐẶT HÀNG";
    document.getElementById("news_page_mobile").innerHTML = "TIN TỨC";
    document.getElementById("register_text_mobile").innerHTML = "Đăng Ký";
    document.getElementById("login_text_mobile").innerHTML = "Đăng Nhập";
    document.getElementById("register_text").innerHTML = "Đăng Ký";
    document.getElementById("login_text").innerHTML = "Đăng Nhập";
    document.getElementById("title_banner_1").innerHTML="KHÁM PHÁ TEYVAT";
    document.getElementById("title_banner_2").innerHTML="40+ CÔNG THỨC MỚI";
    document.getElementById("title_banner_3").innerHTML="TRẢI NGHIỆM BỮA ĂN SẠCH";
    document.getElementById("description_banner_1").innerHTML="5000+ TIN TỨC MỚI MỖI NGÀY";
    document.getElementById("description_banner_2").innerHTML="TRỌN BỘ CÔNG THỨC NẤU ĂN LỤC ĐỊA TEYVAT";
    document.getElementById("description_banner_3").innerHTML="BỮA ĂN TƯƠI NGON GIÀU DINH DƯỠNG";
    document.getElementById("more_button_1").innerHTML="Xem Thêm";
    document.getElementById("more_button_2").innerHTML="Xem Ngay";
    document.getElementById("more_button_3").innerHTML="Đặt Ngay";
    document.getElementById("About_us_des").innerHTML="&nbsp;Trên con đường phiêu lưu của nhà lữ hành thực phẩm đã trở thành một người bạn<br>  không thể thiếu, <b>TEYVAT</b> <font style='color: rgb(44, 117, 44);font-weight: bold;'>FOOD</font>  ở đây giúp nhà lữ hành có được những thông tin<br>  hữu ích nhất về các loại thực phẩm <i>(Công thức nấu ăn, BUFF của thực phẩm ...).</i><br> <br>&nbsp;Bên cạnh đó <b>TEYVAT</b> <font style='color: rgb(44, 117, 44);font-weight: bold;'>FOOD</font> không chỉ hỗ trợ bạn về mặt tinh thần mà còn cả về<br> mặt thể chất. Chúng tôi cung cấp những bữa ăn tươi ngon bổ dưỡng được lấy cảm<br> hứng từ nguyên gốc trong <b>Genshin Impact</b> nhằm cho bạn những trải nghiệm tốt nhất.";
    document.getElementById("Hot_Repices_Title").innerHTML="CÔNG THỨC TIÊU BIỂU";
    document.getElementById("name_repices_1").innerHTML="Tiên Nhảy Tường";
    document.getElementById("name_repices_2").innerHTML="Phúc Lộc Tràn Đầy";
    document.getElementById("name_repices_3").innerHTML="Thập Cẩm Phong Thần";
    document.getElementById("name_repices_4").innerHTML="Đại Hành Quân U";
    document.getElementById("Hot_Food_tittle").innerHTML="THỰC PHẨM TIÊU BIỂU";
    document.getElementById("Protect_enviroment_title").innerHTML="CHUNG TAY BẢO VỆ MÔI TRƯỜNG";
    document.getElementById("linking_partner").innerHTML="ĐỐI TÁC";
    document.getElementById("linking_customer").innerHTML="KHÁCH HÀNG";
    document.getElementById("footer_des_1").innerHTML="<font style='font-weight: bold;color: rgb(172, 222, 223);font-size: 1.2vw;'>CÔNG TY TNHH TEYVATFOOD</font>";
    document.getElementById("footer_des_2").innerHTML="<font style='font-weight: bold;'>Địa chỉ</font> 33 Đường X, KDC Bình Hưng A, Ấp 2, Huyện Bình Chánh A, TP.X";
    document.getElementById("footer_des_3").innerHTML="<font style='font-weight: bold;'>Điện thoại</font> (+84) 932 788 120 [hotline]";
    document.getElementById("footer_des_5").innerHTML="<font style='font-weight: bold;'>MST</font> 0313272749 do Sở kế hoạch và đầu tư TPHCM cấp ngày dd/mm/yyyy";
    document.getElementById("footer_des_7").innerHTML="<font style='font-weight: bold;color: rgb(172, 222, 223);font-size: 1.2vw;'>ĐIỀU KHOẢN CHUNG</font>";
}