if(localStorage.getItem("language") =="en"){
    change_language_english();
}

function change_language_english()
{
    // header
    localStorage.setItem("language","en");
    var en = document.getElementById("english");
    var vn = document.getElementById("vietnamese");
    en.classList.add("choose_language");
    en.classList.remove("unchoose_language");
    vn.classList.remove("choose_language");
    vn.classList.add("unchoose_language");
    var enm = document.getElementById("english_mobile");
    var vnm = document.getElementById("vietnamese_mobile");
    enm.classList.add("choose_language");
    enm.classList.remove("unchoose_language");
    vnm.classList.remove("choose_language");
    vnm.classList.add("unchoose_language");
    document.getElementById("home_page").innerHTML = "HOME";
    document.getElementById("repices_page").innerHTML = "REPICES";
    document.getElementById("order_page").innerHTML = "ORDER";
    document.getElementById("news_page").innerHTML = "NEWS";
    document.getElementById("home_page_mobile").innerHTML = "HOME";
    document.getElementById("repices_page_mobile").innerHTML = "REPICES";
    document.getElementById("order_page_mobile").innerHTML = "ORDER";
    document.getElementById("news_page_mobile").innerHTML = "NEWS";
    document.getElementById("register_text").innerHTML = "Register";
    document.getElementById("login_text").innerHTML = "Login";
    document.getElementById("register_text_mobile").innerHTML = "Register";
    document.getElementById("login_text_mobile").innerHTML = "Login";
    document.getElementById("cart").innerHTML = "SHOPPING CART";
    document.getElementById("item_cart_title_1").innerHTML = "Invigorating Kitty Meal";
    document.getElementById("item_cart_title_2").innerHTML = "Tonkotsu Ramen";
    document.getElementById("item_cart_title_3").innerHTML = "Udon Fuukichi";
    document.getElementById("total_cart").innerHTML = "Total : <font>&nbsp;211,997đ</font>";
    document.getElementById("view_bag").innerHTML = "View Bag";
    document.getElementById("purchase").innerHTML = "Payment";
    // footer
    document.getElementById("footer_des_1").innerHTML="<font style='font-weight: bold;color: rgb(172, 222, 223);font-size: 1.2vw;'>TEYVATFOOD COMPANY LIMITED</font>";
    document.getElementById("footer_des_2").innerHTML="<font style='font-weight: bold;'>Address</font> 33 Đường X, KDC Bình Hưng A, Ấp 2, Huyện Bình Chánh A, TP.X";
    document.getElementById("footer_des_3").innerHTML="<font style='font-weight: bold;'>Phone</font> (+84) 932 788 120 [hotline]";
    document.getElementById("footer_des_5").innerHTML="<font style='font-weight: bold;'>Tax Code</font> 0313272749 do Sở kế hoạch và đầu tư TPHCM cấp ngày dd/mm/yyyy";
    document.getElementById("footer_des_7").innerHTML="<font style='font-weight: bold;color: rgb(172, 222, 223);font-size: 1.2vw;'>TERMS AND CONDITIONS</font>";
    document.getElementById("footer_des_8").innerHTML="<a href='#'>General Regulations Policy</a>";
    document.getElementById("footer_des_9").innerHTML="<a href='#'>Regulations on Payment Methods</a>";
    document.getElementById("footer_des_10").innerHTML="<a href='#'>Shipping Policy</a>";
    document.getElementById("footer_des_11").innerHTML="<a href='#'>Information Privacy Policy</a>";
    // content
    document.getElementById("FAQS_des").innerHTML = "Eager to start a  <font color='black'>TEYVAT </font><font color='green'>FOOD</font> healthy lifestyle? We are here to answer your common inquiries and show you how our program works !"
    let detail = document.getElementsByClassName("FAQ_details");
    detail[0].innerHTML = "<summary><div class='Title'>What is the Model of TEYVAT FOOD ?</div><div class='append'></div></summary>&nbsp;TEYVAT FOOD specializes in providing weekly clean meals prepared in Asian and European style, helping you to pursue a healthy and nutritionally balanced lifestyle.<br><br>&nbsp;Depends on your needs. Whether you are losing weight or gaining muscle, you can choose the right package at the Order page. TEYVAT FOOD will take care of the cooking and delivery every day (Monday to Friday) for you from 2 to 3 servings. Meals are carefully calculated calories and use fresh and healthy ingredients.<br><br>&nbsp;With its 100+ dishes menu, TEYVAT FOOD always ensures that the meals are always rich in protein. , more vegetables and less starch. At the same time, TEYVAT FOOD is committed to saying NO to the use of MSG. All meals are refrigerated to ensure food safety during transportation. Please keep it in the fridge and warm it up in the microwave before eating.";
    detail[1].innerHTML = "<summary><div class='Title'>How to Order?</div><div class='append'></div></summary>&nbsp;You choose the package you want at TEYVAT FOOD.vn/order, don't forget to add to the cart the accompanying products. After adding all the products to the cart, you just need to fill in the delivery information on the website, choose the delivery time and the form of payment COD or transfer.<br><br>&nbsp;After completing Finally, a confirmation email will be automatically sent to the email you registered. Please check your SPAM folder if you do not receive the email. Please note that TEYVAT FOOD does not call to confirm. <br><br>&nbsp;Specially from now on you can choose your favorite dishes in the package. Just click the Edit button after adding the package to the cart and follow the instructions to choose your own.<br><br>&nbsp;If you have any difficulty in the ordering process, please call the number immediately. Hotline of TEYVAT FOOD. 0932 788 120 - 0938 074 120. or inbox Fanpage: m.me/TEYVAT FOODvietnam";
    detail[2].innerHTML = "<summary><div class='Title'>Notes When Using TEYVAT FOOD</div><div class='append'></div></summary>&nbsp;Meals (2 - 3 meals/day) will be delivered to you in the morning of weekdays (from 8 am to 12 pm depending on the region) or the evening before for early delivery requests ( Requests for delivery before 8am will be delivered from 8pm - 10pm the night before)<br><br>&nbsp;To meet food hygiene and safety standards, TEYVAT FOOD's meals are all super-fast frozen by Blast Chiller technology and packaged. immediately after processing to ensure the highest quality and nutrition in food, and at the same time avoid rancidity during transportation.<br><br>&nbsp;As soon as you receive your meal, please immediately put in the refrigerator and reheat in the microwave for 2 minutes before using to ensure the best quality of food.<br><br>&nbsp;The black plastic box of TEYVAT FOOD is PP, exported. Imported from Singapore, it is safe to use in the microwave. However, for the white sauce pot, please remove the lid because the clear plastic lid cannot be used in the microwave.<br><br>&nbsp;For Salads, you can take the paper tray out and heat it up separately. After reheating can be served with a cold crispy salad that will enhance your experience<br><br>&nbsp;For guests who do not have a refrigerator or do not heat with a Microwave / water bath, TEYVAT FOOD not guarantee the best quality of food.";
    detail[3].innerHTML = "<summary><div class='Title'>What's so special about TEYVAT FOOD Meal?</div><div class='append'></div></summary>&nbsp;The ratio of complex carbs (complex carb), fat (fat) and protein (protein) in the servings of TEYVAT FOOD is designed to ensure the best nutritional balance. Most TEYVAT FOOD lunches are fortified with complex carbs to ensure brain activity and maintain productivity in the long run.<br><br>&nbsp;Edible portions. limited to no or few bones, or to use your hands to eat, creating the most convenient and hygienic conditions for customers.<br><br>&nbsp;As soon as you receive your meal, please leave a Immediately put in the refrigerator and reheat in the microwave for 2 minutes before serving to ensure the best quality of food.<br><br>&nbsp;The TEYVAT FOOD menu does not include soups due to seasoning. Spices in soup will reduce the effectiveness in the process of weight loss and the pursuit of a healthy lifestyle. Customers should add a lot of filtered water (at least 2 liters per day) to purify the body<br><br>&nbsp;Some meals will come with sauce, depending on the needs of each guest. Season to taste by yourself.";
    detail[4].innerHTML = "<summary><div class='Title'>How do I want to book a MONTHLY PACKAGE?</div><div class='append'></div></summary>&nbsp;- Monthly price offer only applies to customers who commit to eat continuously for 01 month (4 weeks). If the customer cancels the package midway, TEYVAT FOOD will charge the used meals at the normal price and refund the unused portion. <br><br>&nbsp;- You can reserve your meal package for up to 2 weeks. TEYVAT FOOD will not accept reservations for a longer time. If the guest stops for a longer time, TEYVAT FOOD will charge the used meals at the normal price and refund the unused portion of the value.<br><br>&nbsp;- TEYVAT FOOD will support you. Take a day off for meals in case of unexpected busyness. However, the total number of days off in a month is NOT MORE than 03 days.";
    detail[5].innerHTML = "<summary><div class='Title'>TEYVAT FOOD Food Is Too Pale What To Do?</div><div class='append'></div></summary>&nbsp;Because TEYVAT FOOD restricts the use of sugar and spices in processing, the taste may be a bit bland for most customers. However, you can taste it by tweaking the quantity of the sauce to suit your taste<br><br>&nbsp;The sweetness of TEYVAT FOOD mostly comes from vegetables or brown sugar found in the ingredients. accompanying sauce. TEYVAT FOOD also always encourages guests not to eat too salty or sweet that affects the body's ability to retain water or inflammation. <br><br>&nbsp;When changing seasonings suddenly, you may find bland foods difficult to eat. Many TEYVAT FOOD customers have had similar experiences. However, after using about 3-5 days, your body will get used to it and can feel the change such as a lighter, healthier body, less oily and less acne prone skin.";
    detail[6].innerHTML = "<summary><div class='Title'>How Long To Eat And Which Package To Lose Weight ?</div><div class='append'></div></summary>&nbsp;Depending on each person's physical condition and location (more or less excess fat), you will feel the effect of weight loss and belly fat reduction.<br><br>&nbsp;The initial effect will be noticeable. at the waist in the first 1-2 weeks. Reduce 1-2cm waist circumference. Starting from the 3rd week, you will feel bored and do not want to eat, this is the time when weight loss is most effective. If you strictly follow and follow the TEYVAT FOOD diet in the following weeks, the weight loss effect can be up to 3kg - 5kg in 1 month. Fat loss will be most effective when combined with exercise and gym training.<br><br>&nbsp;During the use of TEYVAT FOOD meal packages, because the amount of calories consumed is reduced compared to the diet. With a normal diet, guests should drink a lot of filtered water or supplement their snacks with low-sweet fruits rich in vitamins (grapefruit, bananas, apples, kiwis, strawberries, avocados) or dried chicken, almonds (eat up to 10 nuts / day). TEYVAT FOOD sells healthy snacks. You can directly contact Fanpage or website for reference.<br><br>&nbsp;It is important that you pursue seriously to achieve the highest efficiency, avoid milk tea or foods with too much starch. (white rice, noodle soup). TEYVAT FOOD encourages customers to return to a normal diet once they have reached their desired weight. Just limit the amount of sugar and starch in the diets.";
    detail[7].innerHTML = "<summary><div class='Title'>TEYVAT FOOD Emissions Too Much Plastic?</div><div class='append'></div></summary>&nbsp;Aware that the use of plastic in its products has a negative impact on the environment, TEYVAT FOOD has a number of policies to help reduce the amount of waste generated by its own products:<br><br>&nbsp;1/ Black plastic containers are used in all servings of TEYVAT FOOD. Therefore, TEYVAT FOOD has a policy of Wash the Box and return it to TEYVAT FOOD to receive a Refund. For every 10 boxes sent back to the shipper, you will immediately receive 10,000 VND back. Please return the box in multiples of 10 so that the staff can refund you. These boxes will be sent back to the manufacturer for recycling. <br><br>&nbsp;2/ It is TEYVAT FOOD's policy to only provide one set of Spoon and Fork a day, TEYVAT FOOD sincerely apologizes for the inconvenience, but would you please help TEYVAT FOOD clean the cutlery and fork and cutlery? Reuse. TEYVAT FOOD thank you very much!<br><br>&nbsp;3/ The nylon meal bag is an eco-friendly Self Degrading Bag. The bag will self-destruct after 3 months in the natural environment, so we hope to be able to partially reduce the negative effects on the surrounding environment.";
    detail[8].innerHTML = "<summary><div class='Title'>Is TEYVAT FOOD Lowcarb?</div><div class='append'></div></summary>&nbsp;This is the most common question TEYVAT FOOD gets. TEYVAT FOOD does not provide DAS or low carb meals.<br><br>&nbsp;Up to 90% of customers perceive lowcarb as zero carb without knowing that effective weight loss diets still require some amount. certain carbs. That is, if you completely cut out foods that contain starch or sugar, and instead eat high amounts of fats and proteins, long-term will cause hormonal imbalance and can lead to many adverse effects. harmful to health due to increased levels of cholesterol and uric acid in the blood.<br><br>&nbsp;The meals of TEYVAT FOOD are balanced between Eastern and Western cuisine, applied based on the University's Healthy Eating Plate principle. Harvard, using good ingredients helps to balance nutrition and maintain a healthy lifestyle.<br><br>&nbsp;- Whole grains (low calories, long-lasting, high in vitamins like whole wheat bread. , brown rice, brown rice noodles, vegetable noodles, pasta)<br><br>&nbsp;- Lots of vegetables and salads without using transfat (oil, margarine).<br><br>&nbspTEYVAT FOOD's cooking style is usually grilled, steamed or stewed and limited frying to ensure high nutritional content while keeping transfat to a minimum.<br><br >&nbsp;Limit the use of white granulated sugar during processing. TEYVAT FOOD will use brown sugar or pure honey in the dips or marinades.";
    detail[9].innerHTML = "<summary><div class='Title'>Why Deliver Eastern Meals?</div><div class='append'></div></summary>&nbsp;TEYVAT FOOD uses a rapid freezing process (Blast Chiller) immediately after cooking. Helps to lower the food temperature at the quad core 120 degrees Celsius to 5 degrees Celsius within 60 minutes, helping to limit the growth of bacteria, while retaining the highest vitamin content, ensuring food quality. Fresh and delicious.<br><br>&nbsp;This standard procedure has been tested by the Food Safety and Hygiene Administration and is widely used in developed countries as well as airline or passenger meals. 5-star luxury hotel.<br><br>&nbsp;TEYVAT FOOD is committed to never using frozen meals to deliver to customers. TEYVAT FOOD servings are freshly prepared every day and kept cool during transit. If food is delivered hot in HCMC weather for a long time, it is easy to spoil and promote the growth of harmful bacteria.<br><br>&nbsp;Please put the servings in the refrigerator as soon as you receive them. to ensure the best quality.";
}
function change_language_vietnamese()
{
    localStorage.setItem("language","vn");
    var en = document.getElementById("english");
    var vn = document.getElementById("vietnamese");
    en.classList.remove("choose_language");
    en.classList.add("unchoose_language");
    vn.classList.add("choose_language");
    vn.classList.remove("unchoose_language");
    var enm = document.getElementById("english_mobile");
    var vnm = document.getElementById("vietnamese_mobile");
    enm.classList.remove("choose_language");
    enm.classList.add("unchoose_language");
    vnm.classList.add("choose_language");
    vnm.classList.remove("unchoose_language");
    document.getElementById("home_page").innerHTML = "TRANG CHỦ";
    document.getElementById("repices_page").innerHTML = "CÔNG THỨC";
    document.getElementById("order_page").innerHTML = "ĐẶT HÀNG";
    document.getElementById("news_page").innerHTML = "TIN TỨC";
    document.getElementById("home_page_mobile").innerHTML = "TRANG CHỦ";
    document.getElementById("repices_page_mobile").innerHTML = "CÔNG THỨC";
    document.getElementById("order_page_mobile").innerHTML = "ĐẶT HÀNG";
    document.getElementById("news_page_mobile").innerHTML = "TIN TỨC";
    document.getElementById("register_text_mobile").innerHTML = "Đăng Ký";
    document.getElementById("login_text_mobile").innerHTML = "Đăng Nhập";
    document.getElementById("register_text").innerHTML = "Đăng Ký";
    document.getElementById("login_text").innerHTML = "Đăng Nhập";
    document.getElementById("cart").innerHTML = "GIỎ HÀNG";
    document.getElementById("item_cart_title_1").innerHTML = "Cơm Mèo Năng Động";
    document.getElementById("item_cart_title_2").innerHTML = "Ramen Xương Hầm";
    document.getElementById("item_cart_title_3").innerHTML = "Mì Udon Fuukichi";
    document.getElementById("total_cart").innerHTML = "Tổng tiền : <font>&nbsp;211,997đ</font>";
    document.getElementById("view_bag").innerHTML = "Xem Giỏ Hàng";
    document.getElementById("purchase").innerHTML = "Thanh Toán";
    document.getElementById("footer_des_1").innerHTML="<font style='font-weight: bold;color: rgb(172, 222, 223);font-size: 1.2vw;'>CÔNG TY TNHH TEYVATFOOD</font>";
    document.getElementById("footer_des_2").innerHTML="<font style='font-weight: bold;'>Địa chỉ</font> 33 Đường X, KDC Bình Hưng A, Ấp 2, Huyện Bình Chánh A, TP.X";
    document.getElementById("footer_des_3").innerHTML="<font style='font-weight: bold;'>Điện thoại</font> (+84) 932 788 120 [hotline]";
    document.getElementById("footer_des_5").innerHTML="<font style='font-weight: bold;'>MST</font> 0313272749 do Sở kế hoạch và đầu tư TPHCM cấp ngày dd/mm/yyyy";
    document.getElementById("footer_des_7").innerHTML="<font style='font-weight: bold;color: rgb(172, 222, 223);font-size: 1.2vw;'>ĐIỀU KHOẢN CHUNG</font>";
    document.getElementById("footer_des_8").innerHTML="<a href='#'>Chính Sách Quy Định Chung</a>";
    document.getElementById("footer_des_9").innerHTML="<a href='#'>Quy Định Hình Thức Thanh Toán</a>";
    document.getElementById("footer_des_10").innerHTML="<a href='#'>Chính Sách Vận Chuyển Giao Hàng</a>";
    document.getElementById("footer_des_11").innerHTML="<a href='#'>Chính Sách Bảo Mật Thông Tin</a>";
    // content
    document.getElementById("FAQS_des").innerHTML = "Bạn muốn trải nghiệm <font color='black'>TEYVAT </font><font color='green'>FOOD</font> nhưng không biết bắt đầu từ đâu? Hãy tham khảo những câu hỏi thường gặp bên dưới nhé !"
    let detail = document.getElementsByClassName("FAQ_details");
    detail[0].innerHTML = "<summary><div class='Title'>Mô Hình Của TEYVAT FOOD Là Gì ?</div><div class='append'></div></summary>&nbsp;TEYVAT FOOD chuyên cung cấp các bữa ăn sạch hàng tuần được chuẩn bị sẵn theo phong cách Á Âu, giúp bạn theo đuổi một phong cách sống khỏe và cân bằng dinh dưỡng.<br><br>&nbsp;Tùy theo nhu cầu của bạn là giảm cân hay tăng cơ, bạn có thể chọn gói sản phẩm phù hợp tại trang Đặt Hàng. TEYVAT FOOD sẽ đảm nhận việc nấu nướng và giao hàng mỗi ngày (thứ 2 đến thứ 6) cho bạn từ 2 đến 3 phần ăn. Các bữa ăn đều được tính toán calories cẩn thận và sử dụng các nguyên liệu tươi ngon tốt cho sức khỏe.<br><br>&nbsp;Với Menu hơn 100 món của mình, TEYVAT FOOD luôn đảm bảo các phần ăn luôn giàu đạm, nhiều rau củ và ít tinh bột. Đồng thời TEYVAT FOOD cam kết nói KHÔNG với việc sử dụng Bột Ngọt. Tất cả các bữa ăn đều được làm lạnh nhằm đảm bảo an toàn thực phẩm trong quá trình vận chuyển. Bạn vui lòng bảo quản trong tủ lạnh và hâm nóng bằng lò vi sóng trước khi ăn.";
    detail[1].innerHTML = "<summary><div class='Title'>Cách Đặt Hàng Như Thế Nào ?</div><div class='append'></div></summary>&nbsp;&nbsp;Bạn chọn gói ăn bạn mong muốn tại TEYVAT FOOD.vn/order, đừng quên thêm vào giỏ hàng các sản phẩm dùng kèm nha. Sau khi cho hết các sản phẩm vào giỏ hàng, bạn chỉ cần điền đầy đủ thông tin giao hàng trên website, chọn thời gian giao hàng và hình thức thanh toán COD hoặc chuyển khoản.<br><br>&nbsp;Sau khi hoàn tất, một email xác nhận sẽ được tự động gửi vào email bạn đăng ký. Bạn vui lòng kiểm tra thư mục SPAM nếu bạn không nhận được email, Bạn lưu ý là TEYVAT FOOD không gọi điện xác nhận nha. <br><br>&nbsp;Đặc biệt từ nay bạn đã có thể tự chọn món yêu thích của mình trong gói ăn. Chỉ cần nhấn vào nút Chỉnh Sửa sau khi thêm gói ăn vào giỏ hàng và làm theo hướng dẫn để tự chọn món.<br><br>&nbsp;Nếu gặp bất cứ khó khăn nào trong quá trình đặt hàng, hãy gọi ngay số Hotline của TEYVAT FOOD. 0932 788 120 - 0938 074 120. hoặc inbox Fanpage : m.me/TEYVAT FOODvietnam";
    detail[2].innerHTML = "<summary><div class='Title'>Các Lưu Ý Khi Sử Dụng TEYVAT FOOD</div><div class='append'></div></summary>&nbsp;Các phần ăn (từ 2 - 3 bữa/ngày) sẽ được giao đến cho bạn vào buổi sáng các ngày trong tuần (từ 8h - 12h tùy khu vực) hoặc vào buổi tối hôm trước đối với các yêu cầu giao sớm (yêu cầu giao trước 8h sáng sẽ được giao từ 8pm - 10pm tối hôm trước)<br><br>&nbsp;Để đạt chuẩn VSATTP, các phần ăn của TEYVAT FOOD đều được cấp đông siêu tốc bằng công nghệ Blast Chiller và đóng gói ngay sau khi chế biến nhằm đảm bảo chất lượng và dinh dưỡng trong thực phẩm ở mức cao nhất, đồng thời tránh ôi thiu trong quá trình vận chuyển.<br><br>&nbsp;Ngay sau khi nhận phần ăn, bạn vui lòng để ngay vào ngăn mát tủ lạnh và hâm lại bằng lò vi sóng trong 02 phút trước khi dùng để đảm bảo chất lượng thức ăn tốt nhất.<br><br>&nbsp;Hộp nhựa đen của TEYVAT FOOD là nhựa PP, hàng xuất khẩu Singapore nên an toàn sử dụng trong lò vi sóng ạ. Tuy nhiên, đối với hủ sốt màu trắng, bạn vui lòng bỏ nắp ra vì nắp nhựa trong không dùng được trong lò vi sóng.<br><br>&nbsp;Đối với các món Salad, bạn có thể lấy khay giấy ra hâm riêng. Sau khi hâm có thể dùng chung với salad lạnh giòn sẽ giúp tăng thêm trải nghiệm của bạn<br><br>&nbsp;Đối với các khách không có tủ lạnh hoặc không hâm nóng bằng Lò Vi Sóng / hấp cách thủy, TEYVAT FOOD không đảm bảo được chất lượng thức ăn tốt nhất.";
    detail[3].innerHTML = "<summary><div class='Title'>Phần Ăn TEYVAT FOOD Có Gì Đặc Biệt ?</div><div class='append'></div></summary>&nbsp;Tỷ lệ tinh bột phức (complex carb), chất béo (fat) và đạm (protein) trong các phần ăn của TEYVAT FOOD được thiết kế để đảm bảo chế độ cân bằng dinh dưỡng tốt nhất. Hầu hết các phần ăn trưa của TEYVAT FOOD được bổ sung tinh bột phức (complex carb) để đảm bảo hoạt động não bộ và duy trì năng suất công việc trong thời gian dài.<br><br>&nbsp;Các phần ăn được hạn chế để không có hoặc ít xương, hay phải sử dụng đến tay để ăn, tạo điều kiện thuận tiện và vệ sinh nhất cho khách hàng.<br><br>&nbsp;Ngay sau khi nhận phần ăn, bạn vui lòng để ngay vào ngăn mát tủ lạnh và hâm lại bằng lò vi sóng trong 02 phút trước khi dùng để đảm bảo chất lượng thức ăn tốt nhất.<br><br>&nbsp;Thực đơn TEYVAT FOOD không bao gồm các loại canh do việc nêm gia vị trong canh sẽ giảm hiệu quả trong quá trình giảm cân và theo đuổi 1 lối sống khỏe. Khách hàng nên bổ sung thật nhiều nước lọc (ít nhất 2 lít mỗi ngày) để thanh lọc cơ thể<br><br>&nbsp;Một số phần ăn sẽ đi kèm với hủ sốt, tùy theo nhu cầu của từng khách có thể tự nêm nếm cho hợp khẩu vị.";
    detail[4].innerHTML = "<summary><div class='Title'>Muốn Đặt GÓI THÁNG Thì Như Thế Nào ?</div><div class='append'></div></summary>&nbsp;- Ưu đãi giá tháng chỉ áp dụng cho khách cam kết ăn liên tục trong 01 tháng (4 tuần). Nếu khách hủy gói giữa chừng, TEYVAT FOOD sẽ tính các phần ăn đã sử dụng theo giá bình thường và hoàn tiền lại cho khách phần giá trị chưa dùng. <br><br>&nbsp;- Quý khách có thể bảo lưu gói ăn trong thời gian tối đa là 02 tuần. TEYVAT FOOD sẽ không nhận bảo lưu trong thời gian lâu hơn. Nếu khách ngưng thời gian dài hơn thì TEYVAT FOOD sẽ tính các phần ăn đã sử dụng theo giá bình thường và hoàn tiền lại cho khách phần giá trị chưa dùng.<br><br>&nbsp;- TEYVAT FOOD sẽ hỗ trợ quý khách nghỉ ngày ăn trong trường hợp bận đột xuất. Tuy nhiên tổng số ngày ngưng trong 1 tháng KHÔNG QUÁ 03 ngày.";
    detail[5].innerHTML = "<summary><div class='Title'>Thức Ăn TEYVAT FOOD Nhạt Quá Phải Làm Sao?</div><div class='append'></div></summary>&nbsp;Do TEYVAT FOOD hạn chế sử dụng đường và các loại gia vị trong chế biến, nên khẩu vị có thể hơi nhạt đối với đa số khách hàng. Tuy nhiên, bạn có thể nêm nếm bằng cách tinh chỉnh định lượng của hủ sốt để phù hợp với khẩu vị của bạn<br><br>&nbsp;Chất ngọt của TEYVAT FOOD đa phần đến từ rau củ hoặc đường nâu có trong các hủ sốt dùng kèm. TEYVAT FOOD cũng luôn khuyến khích khách không nên ăn quá mặn hoặc ngọt ảnh hưởng đến khả năng tích nước hoặc viêm nhiễm của cơ thể. <br><br>&nbsp;Khi thay đổi gia vị một cách đột ngột thì bạn có thể cảm thấy thức ăn nhạt rất khó ăn. Rất nhiều khách hàng của TEYVAT FOOD đều có trải nghiệm tương tự. Tuy nhiên, sau khi dùng khoảng 3 -  5 ngày, cơ thể bạn sẽ làm quen và có thể cảm thấy được sự thay đổi như cơ thể khỏe khoắn nhẹ nhàng hơn, da mặt ít nhờn và đỡ mụn hơn.";
    detail[6].innerHTML = "<summary><div class='Title'>Ăn Bao Lâu Và Ăn Gói Nào Để Giảm Cân ?</div><div class='append'></div></summary>&nbsp;Tùy theo thể trạng và cơ địa của từng người (nhiều hoặc ít mỡ thừa) mà bạn sẽ cảm nhận được hiệu quả giảm cân và giảm mỡ bụng.<br><br>&nbsp;Hiệu quả bước đầu sẽ nhận thấy rõ nhất ở vòng eo trong 1- 2 tuần đầu. Giảm từ 1-2cm vòng bụng. Bắt đầu từ tuần thứ 3, bạn sẽ cảm thấy ngán và ko muốn ăn, đây là thời điểm giảm cân phát huy hiệu quả nhất. Nếu bạn tuân thủ nghiêm ngặt và theo đuổi chế độ ăn của TEYVAT FOOD trong những tuần kế tiếp, hiệu quả giảm cân có thể lên đến 3kg - 5kg trong 1 tháng. Việc giảm mỡ sẽ đạt hiệu quả tối đa khi kết hợp với việc tập luyện thể dục và gym.<br><br>&nbsp;Trong quá trình sử dụng các gói ăn của TEYVAT FOOD, vì lượng calories nạp vào giảm so với chế độ ăn bình thường nên các khách nên uống nhiều nước lọc hoặc bổ sung các bữa xế bằng trái cây ít ngọt giàu vitamin (bưởi, chuối, táo, kiwi, dâu, bơ) hoặc khô gà, hạnh nhân (ăn tối đa 10 hạt/ngày). TEYVAT FOOD có bán các sản phẩm dùng kèm ăn vặt lành mạnh. Bạn có thể liên hệ trực tiếp Fanpage hoặc website để tham khảo.<br><br>&nbsp;Quan trọng là bạn phải theo đuổi nghiêm túc để đạt được hiệu quả cao nhất, tránh trà sữa hoặc các thực phẩm quá nhiều tinh bột (cơm trắng, bún phở). TEYVAT FOOD khuyến khích khách hàng khi đã đạt được cân nặng mong muốn có thể quay lại chế độ ăn bình thường. Chỉ cần hạn chế lượng đường và tinh bột trong các khẩu phần ăn.";
    detail[7].innerHTML = "<summary><div class='Title'>TEYVAT FOOD Thải Ra Nhựa Nhiều Quá ?</div><div class='append'></div></summary>&nbsp;Nhận biết được việc sử dụng nhựa trong các sản phẩm của mình gây tác động tiêu cực đến môi trường, TEYVAT FOOD có một số chính sách nhằm giúp giảm bớt lượng rác thải của chính sản phẩm mình gây ra:<br><br>&nbsp;1/ Hộp nhựa đen được sử dụng trong tất cả các phần ăn của TEYVAT FOOD. Vì vậy, TEYVAT FOOD có chính sách Rửa Sạch Hộp và gửi lại cho TEYVAT FOOD để nhận được Hoàn Tiền. Cứ mỗi 10 hộp gửi trả lại cho shipper, bạn sẽ nhận lại ngay 10,000 vnd. Bạn vui lòng hoàn trả hộp theo bội số của 10 để nhân viên tiện hoàn tiền lại cho bạn. Các hộp này sẽ được gửi lại cho nhà sản xuất để tái chế. <br><br>&nbsp;2/ Chính sách của TEYVAT FOOD là chỉ cung cấp một bộ Muỗng Nĩa mỗi ngày, TEYVAT FOOD thành thật xin lỗi vì sự bất tiện này, nhưng bạn vui lòng giúp TEYVAT FOOD rửa sạch muỗng nĩa và sử dụng lại. TEYVAT FOOD cám ơn bạn rất nhiều!<br><br>&nbsp;3/ Túi nylon đựng các phần ăn là Túi Tự Hủy thân thiện với môi trường. Túi sẽ tự hủy sau 3 tháng ngoài môi trường tự nhiên nên bên mình hy vọng sẽ có thể giảm thiểu được một phần nào tác hại tiêu cực đến môi trường xung quanh.";
    detail[8].innerHTML = "<summary><div class='Title'>TEYVAT FOOD Có Phải Là Lowcarb?</div><div class='append'></div></summary>&nbsp;Đây là câu hỏi phổ biến nhất mà TEYVAT FOOD nhận được. TEYVAT FOOD không cung cấp các phần ăn theo chế độ DAS hoặc lowcarb.<br><br>&nbsp;Có đến 90% các khách quan niệm lowcarb là zero carb mà ko biết rằng chế độ ăn giảm cân hiệu quả vẫn cần một lượng carb nhất định. Tức là nếu cắt bỏ hoàn toàn các thực phẩm có chứa tinh bột hoặc đường, thay vào đó lại nạp vào các chất béo và đạm với hàm lượng cao, lâu dài sẽ gây mất cân bằng nội tiết tố và có thể dẫn đến nhiều tác hại cho sức khỏe do lượng Cholesterol và Acid uric trong máu tăng.<br><br>&nbsp;Các khẩu phần ăn của TEYVAT FOOD được dung hòa giữa ẩm thực Đông Tây, áp dụng dựa trên nguyên tắc Healthy Eating Plate của Đại học Harvard, sử dụng các nguyên liệu tốt giúp cân bằng dinh dưỡng và duy trì một lối sống khỏe.<br><br>&nbsp;- Các loại ngũ cốc nguyên hạt (calories thấp, no lâu, nhiều vitamin như bánh mì nguyên hạt, cơm gạo lức, bún mì gạo lức, mì rau củ, pasta)<br><br>&nbsp;- Nhiều rau củ và salad mà ko sử dụng transfat (dầu ăn, bơ magarine).<br><br>&nbsp;Phong cách nấu nướng của TEYVAT FOOD thường sẽ là nướng, hấp hoặc hầm và hạn chế chiên dầu mỡ để đảm bảo hàm lượng dinh dưỡng được giữ lại cao trong khi hạn chế được lượng transfat đến mức thấp nhất.<br><br>&nbsp;Hạn chế sử dụng đường cát trắng trong quá trình chế biến. TEYVAT FOOD sẽ sử dụng đường nâu hoặc mật ong nguyên chất trong các phần sốt chấm hoặc sốt ướp thịt.";
    detail[9].innerHTML = "<summary><div class='Title'>Tại Sao Lại Giao Phần Ăn Cấp Đông ?</div><div class='append'></div></summary>&nbsp;TEYVAT FOOD sử dụng quy trình cấp đông làm lạnh nhanh (Blast Chiller) ngay sau khi nấu chín. Giúp hạ nhiệt độ thực phẩm tại lõi tứ 120 độ C xuống 5 độ C trong vòng 60 phút, giúp hạn chế sự phát triển của vi khuẩn, đồng thời giữ lại được hàm lượng vitamin cao nhất, đảm bảo được chất lượng thức ăn luôn tươi ngon.<br><br>&nbsp;Quy trình tiêu chuẩn này đã được kiểm nghiệm bởi Cục Quản lý Vệ Sinh An Toàn Thực Phẩm và được áp dụng rộng rãi ở các nước phát triển cũng như các suất ăn hàng không hoặc khách sạn 5 sao cao cấp.<br><br>&nbsp;TEYVAT FOOD cam kết không bao giờ sử dụng các phần ăn đông lạnh để giao đến cho khách hàng. Các phần ăn của TEYVAT FOOD luôn được chuẩn bị mới mỗi ngày và được giữ mát trong suốt quá trình vận chuyển. Nếu thực phẩm giao nóng trong thời tiết TPHCM trong thời gian dài rất dễ bị hư hỏng và thúc đẩy các vi khuẩn gây hại phát triển.<br><br>&nbsp;Bạn vui lòng bỏ các phần ăn vào tủ lạnh ngay khi nhận để đảm bảo chất lượng tốt nhất.";
}